;config file moduleBox

[SYSTEM]
;12v 25w
deviceName = audiostickPlus
boardVersion = 4

[SLOT_0]
;speaker 100-001
mode = mp3Player
options = volume:90

[SLOT_1]
mode = SD_card

[SLOT_2]
;button 'магнитная база с герконом 100-004'
mode = button_smartLed
options = buttonInverse
crosslink = button_2/event/press:1->player_0/action/play:#, button_2/event/press:0->player_0/action/stop:1

[SLOT_3]
;ledButton 300-001
mode = button_led
crosslink = button_3/event/press:1->led_3/action/enable:1, button_3/event/press:1->led_4/action/enable:0, button_3/event/press:1->led_5/action/enable:0, button_3/event/press:1->player_0/action/shift:0

[SLOT_4]
;ledButton 300-001
mode = button_led
crosslink = button_4/event/press:1->led_4/action/enable:1, button_4/event/press:1->led_3/action/enable:0, button_4/event/press:1->led_5/action/enable:0, button_4/event/press:1->player_0/action/shift:1

[SLOT_5]
;ledButton 300-001
mode = button_led
crosslink = button_5/event/press:1->led_5/action/enable:1, button_5/event/press:1->led_3/action/enable:0, button_5/event/press:1->led_4/action/enable:0, button_5/event/press:1->player_0/action/shift:2

[SLOT_6]
mode = startup
crosslink = startup_6/event/started:1->led_3/action/enable:1, startup_6/event/started:1->player_0/action/shift:0
