  ;config file moduleBox. Ver:3.59 

[SYSTEM] 
;12v 100w mountPlate
deviceName = mbs 
boardVersion=4

[LAN] 
LAN_enable = 1
DHCP=0
ipAdress= 10.10.3.213
netMask=255.255.255.0

[MQTT] 
mqttBrokerAdress = 10.10.3.202

[SLOT_0] 
;servoStepper HSS42 48V 'привод элеватора'
mode = stepper 
options = maxSpeed:13000, accel:20000, homingDir:up, homingTimeout:300, refreshRate:40, homingSpeed:13000
crosslink = stepper_0/event/homingState:done->stepper_0/action/moveToInc: 40000

[SLOT_1] 
;inductiveSensor LJ18 'датчик элеватора'
mode = in_out 
options = empty 
crosslink = in_1/event/val:@ ->stepper_0/action/setHomingSensor:@

[SLOT_2] 
; solenoid 'соленоид змейки'
mode = out_2ch 
options = defState_0:1, inverse_0:1 
crosslink = empty 

[SLOT_3] 
mode = in_out 
;opticSensor G18-3A30NC 'датчик после змейки'
options = empty 
crosslink = empty 

[SLOT_4] 
mode = empty 
options = empty 
crosslink = empty 

[SLOT_5] 
mode = empty
options = empty 
crosslink = empty 

[SLOT_6] 
mode = listOfActions 
options = 
crosslink = 

[SLOT_7] 
mode = startup 
options = delay:1500 
crosslink = startup_7/event/started->stepper_0/action/goHome 

[SLOT_8] 
mode = timer 
options = 
crosslink = timer_8/event/timerEnd->stepper_0/action/goHome


[HELP] 
; http://mbwiki.ru/ 
