  ;config file moduleBox. Ver:3.73 
  
[SYSTEM]  
;12v 100w mountPlate
deviceName = mbw 
boardVersion=4

[LAN] 
LAN_enable = 1
DHCP = 0
ipAdress = 10.10.3.211
netMask = 255.255.255.0 

[MQTT] 
mqttBrokerAdress =  192.168.1.92

[SLOT_0] 
;servoStepper IHSV57 48V
mode = stepper 
options = maxSpeed:40001, accel:40001, refreshRate:40, homingDir:up, homingTimeout:60
crosslink = stepper_0/event/homingState:done->stepper_0/action/moveToInc:-1050000   

[SLOT_1] 
; opticSensor_x2 BS5-T2M OCjumper
mode = in_2ch 
options = empty 
crosslink = in_1/event/ch_0:@->stepper_0/action/setHomingSensor:@, in_1/event/ch_1:@->stepper_2/action/setHomingSensor:@

[SLOT_2] 
;servoStepper IHSV57 48V
mode = stepper 
options = maxSpeed:76924, accel:76924, refreshRate:40, homingDir:up, homingTimeout:60
crosslink = stepper_2/event/homingState:done->stepper_2/action/moveToInc:-1065000  

[SLOT_3] 
; opticSensor G18-3A30NC
mode = in_out 
options = empty 
crosslink =  

[SLOT_4]
; solenoid 
mode = out_2ch 
options = defState_0:1, inverse_0:1
crosslink = empty 

[SLOT_5] 
;none
mode = relay 
options = empty 
crosslink = empty 

[SLOT_6] 
mode = listOfActions
options = empty 
crosslink = empty 

[SLOT_7]
mode=startup
options=delay:1500
crosslink=startup_7/event/started->stepper_0/action/goHome, startup_7/event/started->stepper_2/action/goHome

[HELP] 
; http://mbwiki.ru/ 
