  ;config file moduleBox. Ver:3.59   

[SYSTEM] 
;12v 100w mountPlate
deviceName = mbe 
boardVersion=4

[LAN] 
LAN_enable = 1
DHCP=0
ipAdress= 10.10.3.210
netMask=255.255.255.0

[MQTT] 
mqttBrokerAdress = 10.10.3.202

[SLOT_0] 
;servoStepper HSS42 48V 'привод элеватора'
mode = stepper 
options = maxSpeed:7000, accel:3000, refreshRate:40, homingDir:up, homingSpeed:7000, homingTimeout:300
crosslink = stepper_0/event/homingState:done->stepper_0/action/moveToInc:4000

[SLOT_1] 
;inductiveSensor LJ18 'датчик элеватора'
mode = in_out 
options = inInverse 
crosslink = in_1/event/val:@->stepper_0/action/setHomingSensor:@ 

[SLOT_2] 
; solenoid 'соленоид зигзага'
mode = out_2ch 
options = defState_0:1, inverse_0:1
crosslink = empty 

[SLOT_3] 
;opticSensor G18-3A30NC 'датчик после зигзага'
mode = in_2ch 
options = inverse_0, inverse_1 
crosslink = empty 

[SLOT_4] 
mode = empty 
options = empty
crosslink = empty 

[SLOT_5] 
mode = empty 
options = empty 
crosslink = empty 

[SLOT_6] 
mode = listOfActions 
options = empty 
crosslink = empty 


[HELP] 
; http://mbwiki.ru/ 
