  ;config file moduleBox. Ver:3.73  
     
[SYSTEM]  
;12v 100w mountPlate
deviceName = mbd 
boardVersion=4 

[LAN] 
LAN_enable = 1
DHCP=0
ipAdress= 10.10.3.214
netMask=255.255.255.0

[MQTT] 
mqttBrokerAdress = 10.10.3.202

[SLOT_0] 
;servoStepper HSS42 48V 'привод диспенсора'
mode = stepper 
options = maxSpeed:60000, accel:60000, refreshRate:40, homingDir:up, homingTimeout:60
crosslink = stepper_0/event/homingState:done->stepper_0/action/moveToInc:100000

[SLOT_1] 
;hallSensor 'датчик диспенсора'
mode = in_out
options = empty 
crosslink = in_1/event/val:@->stepper_0/action/setHomingSensor:@

[SLOT_2] 
;'привод задвижки' 5V DCDC
mode = PPMservo 
options = startPos:2000
crosslink =

[SLOT_3] 
;opticSensor G18-3A30NC 'мало шаров'
mode = in_out 
options = inInverse 
crosslink = 

[SLOT_4] 
;RGBstrip 12V
mode = pwmLeds 
options = RGBcolor:0 0 0
crosslink = empty 

[SLOT_5] 
mode = empty
options = empty
crosslink = empty 

[SLOT_6] 
mode = listOfActions
options = empty 
crosslink = empty 

[SLOT_7]
mode=timer
options=
crosslink= timer_7/event/timerEnd->servo_2/action/setPulse:1000,timer_7->timer_8/action/start:2000

[SLOT_8]
mode=timer
options=
crosslink= timer_8/event/timerEnd->servo_2/action/setPulse:2000, timer_8->pwmLeds_4/action/setRGB:0 0 0

[HELP] 
; http://mbwiki.ru/ 
