;config file moduleBox

[SYSTEM]
deviceName = audiostick
boardVersion = 4

[SLOT_0]
;speaker 100-001
mode = mp3Player
options = volume:75
crosslink = player_0/event/endOfTrack:#->player_0/action/play:#

[SLOT_1]
mode = SD_card

[SLOT_2]
;button 'магнитная база с герконом 100-004'
mode = button_led
options = buttonInverse
crosslink = button_2/event/press:1->player_0/action/play:0, button_2/event/press:0->player_0/action/stop:1
