  ;config file moduleBox. Ver:3.73  
   
[SYSTEM]  
;5v 100w mountPlate
deviceName = mbb
boardVersion=4

[LAN] 
LAN_enable = 1
DHCP=0
ipAdress= 10.10.3.212
netMask=255.255.255.0

[MQTT] 
mqttBrokerAdress = 10.10.3.202

[SLOT_0] 
;buttonSmartLed 300-004
mode = button_smartLed 
options = ledEnableOnStart:1
crosslink = 

[SLOT_1] 
;buttonSmartLed 300-004
mode = button_smartLed 
options =  ledEnableOnStart:1
crosslink = 

[SLOT_2] 
;buttonSmartLed 300-004
mode = button_smartLed 
options =  ledEnableOnStart:1
crosslink = 

[SLOT_3] 
;buttonSmartLed 300-004
mode = button_smartLed 
options =  ledEnableOnStart:1
crosslink = 

[SLOT_4] 
;hallSensor_x2 41F 'энкодер свитка'
mode = encoderInc 
options = absolute, maxVal:5000, minVal:0, dirInverse
crosslink = empty 

[SLOT_5] 
;opticSensor_x2 BS5-T2M OCjumper 'энкодер штурвала'
mode = encoderInc 
options = absolute, maxVal:5000, minVal:0
crosslink = empty 

[HELP]  
; http://mbwiki.ru/ 
