;config file moduleBox

[SYSTEM]
deviceName = retroTelephone
boardVersion = 4

[SLOT_0]
;speaker 'динамик трубки'
mode = mp3Player
crosslink = player_0/event/endOfTrack:#->player_0/action/play:#

[SLOT_1]
mode = SD_card

[SLOT_2]
;button 'рычаг трубки'
mode = button_led
crosslink = button_2/event/press:1->player_0/action/play:#, button_2/event/press:0->player_0/action/stop:1

[SLOT_3]
;rotaryDial OCjumper
mode = dialer
options = numberMaxLenght:1
crosslink = dialer_3/event/val:@->whitelist_4/action/check:@

[SLOT_4]
mode = whitelist
