;config file moduleBox

[SYSTEM]
deviceName = spinner
boardVersion = 4

[LAN]
LAN_enable = 1
DHCP = 0
ipAdress = 192.168.0.33
netMask = 255.255.255.0
gateWay = 192.168.0.1

[MQTT]
mqttBrokerAdress = 192.168.0.1

[SLOT_0]
;as5600
mode = encoderAS5600
options = numOfPos:9, absolute
crosslink = encoder_0/event/val:@->led_1/action/setPos:@

[SLOT_1]
;buttonSmartLed 300-004
mode = button_ledRing
options = numOfPos:9, increment:40
crosslink = button_1/event/press:@->led_1/action/enable:@
